title: sdcweb.tk
description: Home of SDC - Index of services and providers used by SDC for clearnet sites.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
plugins:
  - jekyll-target-blank
